markdown: redcarpet
highlighter: null
permalink: /:title

url: http://kellygrape.github.io/com402/
baseurl: /com402

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
collections:
  assignments:
    output: true