markdown: redcarpet
highlighter: null
permalink: /:title

url: http://spring2015.professorpipe.com/
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
collections:
  assignments:
    output: true